schema {
    query: Query
    mutation: Mutation
    subscription: Subscription
}

type Query {
    getPublicArticle(id: String!): OutlineRecord
}

type Subscription {
    updatedArticle(id: String!): OutlineRecord
    @aws_subscribe(mutations: ["updateArticle"])
}

type Mutation {
    addArticle(url: String!): OutlineSecretRecord
    updateArticle(id: String!, secretId: String!, html: String!): OutlineRecord
    deleteArticle(id: String!, secretId: String!): OutlineRecord
}

type Article {
    title: String
    originalText: String
    originalHtml: String
    html: String
    authors: String
    publishDate: String
    sourceUrl: String
    lang: String
}

type OutlineRecord {
    id: String!
    article: Article
    createdAt: Int
}

type OutlineSecretRecord {
    id: String!
    secretId: String!
    article: Article
    createdAt: Int
}